<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Delete' => 'Elimina',
    'Entity' => '',
    'ID' => '',
    'Reply' => 'Rispondi',
    'Add a comment...' => 'Aggiungi un commento...',
    'Click here to cancel reply.' => 'Clicca qui per annullare la risposta',
    'Comment' => 'Commento',
    'Comment has been deleted.' => 'Il commento è stato cacellato',
    'Comment has been saved.' => 'Il commento è stato salvato',
    'Comment has not been deleted. Please try again!' => 'Il commento non è stato cancellato. Riprova!',
    'Comment was deleted.' => 'Commento cancellato.',
    'Comments Management' => 'Gestione Commenti',
    'Created by' => 'Creato da',
    'Created date' => 'Creato il',
    'Level' => 'Livello',
    'Oops, something went wrong. Please try again later.' => 'Oops, qualcosa è andato storto. Riprova più tardi.',
    'Related to' => 'Relativo a',
    'Select Author' => 'Seleziona Autore',
    'Select Status' => 'Seleziona Stato',
    'Status' => 'Stato',
    'Submit' => 'Invia',
    'The "entityIdAttribute" value for widget model cannot be empty.' => 'Il valore di "entityIdAttribute" per il widget non può essere vuoto.',
    'The "model" property must be set.' => 'La proprietà modello non può essere vuoto',
    'The requested page does not exist.' => 'La pagina richiesta non esiste',
    'Update' => 'Aggiorna',
    'Update Comment: ' => 'Aggiorna Commento:',
    'Updated by' => 'Modificato da',
    'Updated date' => 'Modificato il',
];
